seed: 1
record_video: yes

environment:
  simulation_dt: 0.001
  control_dt: 0.01
  max_time: 11.0
  render: True

  num_envs: 96
  eval_every_n: 20
  visualize_eval: True
  num_threads: 40

  reward:
    position:
      coeff: -0.004
    relPosition:
      coeff: 0.0
    thrust:
      coeff: 0.0 # maybe not a good choice
    orientation:
      coeff: 0.0
    angularVelocity:
      coeff: 0.0 # maybe not a good choice for


architecture:
  policy_net: [64, 64]
  value_net: [64, 64]
  activation_fn: nn.LeakyReLU
  deterministic_policy: False

helper:
  normalize_ob: False
  update_mean: True
  scale_action: False # because scaling is done in Environment.hpp for better performance
  clip_action: False # either scale or clip action to [-1, 1]. Also works fine.

hyperparam:
  num_mini_batches: 3
  num_learning_epochs: 16
  shuffle: False
  Gamma: 0.995
  Lambda: 0.95
  clip_param: 0.2
  learning_rate: 0.001
  value_loss_coef: 0.5
  use_clipped_value_loss: True # if True: PPO2, False: PPO
  entropy_coef: 0.001


