<?xml version="1.0"?>
<!--
    ITM_Quadrocopter 2020
    Values from file named "trägheitsmomente_quadrocopter.dat"
-->

<robot name="ITM_Quadrocopter" xmlns:xacro="http://ros.org/wiki/xacro">
    <!-- Properties of the ITM_Quadrocopter -->
    <xacro:property name="namespace" value="$(arg namespace)" />
    <xacro:property name="rotor_velocity_slowdown_sim" value="10" />    
    <xacro:property name="use_mesh_file" value="true" />
    <xacro:property name="mesh_file" value="package://rotors_description/meshes/test2.dae" />
    <!-- itm_quadroctor //ITM_Quadrocopter-->
    <xacro:property name="mass" value="1.659" /> <!-- [kg] -->            
    <xacro:property name="body_width" value="0.1" /> <!-- [m] -->       
    <xacro:property name="body_height" value="0.27" /> <!-- [m] -->     
    <xacro:property name="mass_rotor" value="0.017" /> <!-- [kg] -->
    <xacro:property name="arm_length" value="0.2419" />
    <xacro:property name="sin45" value="0.70710678118" />
    <xacro:property name="cos45" value="0.70710678118" /> <!-- [m] -->      
    <xacro:property name="rotor_offset_top" value="0.071" /> <!-- [m] -->

    <!-- Following values are not edited because of missing informations -->
    
    <xacro:property name="radius_rotor" value="0.12" /> <!-- [m] -->
    <xacro:property name="motor_constant" value="8.54858e-06" /> <!-- [kg m/s^2] -->
    <xacro:property name="moment_constant" value="0.016" /> <!-- [m] -->
    <xacro:property name="time_constant_up" value="0.0125" /> <!-- [s] -->
    <xacro:property name="time_constant_down" value="0.025" /> <!-- [s] -->
    <xacro:property name="max_rot_velocity" value="838" /> <!-- [rad/s] -->
    <xacro:property name="rotor_drag_coefficient" value="8.06428e-05" />
    <xacro:property name="rolling_moment_coefficient" value="0.000001" />

    <!-- Property Blocks -->
    <!-- Information from trägheitsmomente_quadrocopter.dat are in kg*mm². Changing to kg*m² by multiplying with
         a factor of 10^⁻6 -->
    <xacro:property name="body_inertia">
        <inertia ixx="6.687e-03" ixy="-2.4e-04" ixz="3.467e-04" iyy="1.01e-02" iyz="1.458e-04" izz="9.96e-03" /> <!-- [kg m^2] [kg m^2] [kg m^2] [kg m^2] [kg m^2] [kg m^2] -->
    </xacro:property>

    <!-- inertia of a single rotor, assuming it is a cuboid. Height=3mm, width=15mm -->
    <xacro:property name="rotor_inertia">
        <xacro:box_inertia x="${radius_rotor}" y="0.015" z="0.003" mass="${mass_rotor*rotor_velocity_slowdown_sim}" />
    </xacro:property>

    <!-- Included URDF Files -->
    <xacro:include filename="$(find rotors_description)/urdf/multirotor_base.xacro" />

    <!-- Instantiate multirotor_base_macro once -->
    <xacro:multirotor_base_macro
        robot_namespace="${namespace}"
        mass="${mass}"
        body_width="${body_width}"
        body_height="${body_height}"
        use_mesh_file="${use_mesh_file}"
        mesh_file="${mesh_file}">
        <xacro:insert_block name="body_inertia" />
    </xacro:multirotor_base_macro>

    <!-- Instantiate rotors -->
    <xacro:vertical_rotor
        robot_namespace="${namespace}"
        suffix="frontleft"
        direction="cw"
        motor_constant="${motor_constant}"
        moment_constant="${moment_constant}"
        parent="${namespace}/base_link"
        mass_rotor="${mass_rotor}"
        radius_rotor="${radius_rotor}"
        time_constant_up="${time_constant_up}"
        time_constant_down="${time_constant_down}"
        max_rot_velocity="${max_rot_velocity}"
        motor_number="1"
        rotor_drag_coefficient="${rotor_drag_coefficient}"
        rolling_moment_coefficient="${rolling_moment_coefficient}"
        color="Red"
        use_own_mesh="false"
        mesh="">
        <origin xyz="${sin45*arm_length} ${cos45*arm_length} ${rotor_offset_top}" rpy="0 0 0" />
        <xacro:insert_block name="rotor_inertia" />
    </xacro:vertical_rotor>

    <xacro:vertical_rotor
        robot_namespace="${namespace}"
        suffix="frontright"
        direction="ccw"
        motor_constant="${motor_constant}"
        moment_constant="${moment_constant}"
        parent="${namespace}/base_link"
        mass_rotor="${mass_rotor}"
        radius_rotor="${radius_rotor}"
        time_constant_up="${time_constant_up}"
        time_constant_down="${time_constant_down}"
        max_rot_velocity="${max_rot_velocity}"
        motor_number="0"
        rotor_drag_coefficient="${rotor_drag_coefficient}"
        rolling_moment_coefficient="${rolling_moment_coefficient}"
        color="Red"
        use_own_mesh="false"
        mesh="">
        <origin xyz="${sin45*arm_length} -${cos45*arm_length} ${rotor_offset_top}" rpy="0 0 0" />
        <xacro:insert_block name="rotor_inertia" />
    </xacro:vertical_rotor>

    <xacro:vertical_rotor
        robot_namespace="${namespace}"
        suffix="backleft"
        direction="ccw"
        motor_constant="${motor_constant}"
        moment_constant="${moment_constant}"
        parent="${namespace}/base_link"
        mass_rotor="${mass_rotor}"
        radius_rotor="${radius_rotor}"
        time_constant_up="${time_constant_up}"
        time_constant_down="${time_constant_down}"
        max_rot_velocity="${max_rot_velocity}"
        motor_number="2"
        rotor_drag_coefficient="${rotor_drag_coefficient}"
        rolling_moment_coefficient="${rolling_moment_coefficient}"
        color="Blue"
        use_own_mesh="false"
        mesh="">
        <origin xyz="-${sin45*arm_length} ${cos45*arm_length} ${rotor_offset_top}" rpy="0 0 0" />
        <xacro:insert_block name="rotor_inertia" />
    </xacro:vertical_rotor>

    <xacro:vertical_rotor
        robot_namespace="${namespace}"
        suffix="backright"
        direction="cw"
        motor_constant="${motor_constant}"
        moment_constant="${moment_constant}"
        parent="${namespace}/base_link"
        mass_rotor="${mass_rotor}"
        radius_rotor="${radius_rotor}"
        time_constant_up="${time_constant_up}"
        time_constant_down="${time_constant_down}"
        max_rot_velocity="${max_rot_velocity}"
        motor_number="3"
        rotor_drag_coefficient="${rotor_drag_coefficient}"
        rolling_moment_coefficient="${rolling_moment_coefficient}"
        color="Blue"
        use_own_mesh="false"
        mesh="">
        <origin xyz="-${sin45*arm_length} -${cos45*arm_length} ${rotor_offset_top}" rpy="0 0 0" />
        <xacro:insert_block name="rotor_inertia" />
    </xacro:vertical_rotor>
</robot>